name: CI_CD Workflow

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - main

jobs:
    build-feature:
        if: startsWith(github.ref, 'refs/heads/feature/')
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        # Paso 2: Configurar Google Cloud SDK
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}


           # Paso 3: Autenticar Docker con Google Container Registry (GCR)
        - name: Authenticate Docker with GCR
          run: gcloud auth configure-docker us-central1-docker.pkg.dev

        # Paso 4: Construir la imagen Docker
        - name: Build Docker image
          run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.name_app}}:latest .

        # Paso 5: Subir la imagen a GCR
        - name: Push Docker image to GCR
          run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.name_app}}:latest
